.service (systemd unit config)
ramizhub/inspector pull request #1
Opened 2023-03-02 09:05 UTC by ramizhub

2023-03-02 17:29 UTC, suletm requested changes

2023-03-02 17:29 UTC, suletm commented on systemd/systemdconf.service
> +ExecStart=/home/ramiz/inspector/a.out
Service binaries must be placed in a separate directory. You can create a new separate directory structure in /opt like this:

/opt
 - /opt/bin
 - /opt/etc
 
and place your binary into /opt/bin.

2023-03-02 17:29 UTC, suletm commented on systemd/systemdconf.service
> +WorkingDirectory=/home/ramiz
Same issue, use separate directory.

2023-03-02 17:29 UTC, suletm commented on systemd/systemdconf.service
> +Group=ramiz
Create a separate user for this service.

2023-03-02 17:49 UTC, ramizhub commented on systemd/systemdconf.service
> +Group=ramiz
Does it have a purpose? I really wonder why you need to create a new one.

2023-03-02 18:00 UTC, ramizhub commented on systemd/systemdconf.service
> +ExecStart=/home/ramiz/inspector/a.out
The binary is in my /home/inspector folder (but ignored by git). I will compile it often, and changing the old binary in /opt/bin every time will be a strange solution. Can I use symlink in /opt/bin? (link to the binary in /home/inspector)

2023-03-02 18:13 UTC, ramizhub commented on systemd/systemdconf.service
> +ExecStart=/home/ramiz/inspector/a.out
By the way, for what we may need /opt/etc ?

2023-03-03 02:13 UTC, suletm commented on systemd/systemdconf.service
> +Group=ramiz
Services run under their own users due to isolation principle. If the service is hacked, then your username will be affected. Assuming it's an admin user (aka has sudo access) it'll quickly turn into a whole system compromise. Therefore services are either run under a completely separate restricted user.

2023-03-03 02:17 UTC, suletm commented on systemd/systemdconf.service
> +ExecStart=/home/ramiz/inspector/a.out
>  I suppose it will be something like this: g++ main.cpp -o /opt/bin/a.out. 
yes, but the compilation process will done by CI/CD or somewhere else. You will not compile on the server. The server will receive the compiled binary. 

> Let's say it will be in /opt/bin and refer to /home/inspector/main.cpp

It's possible, but then again if you are going to add more services in future, then you're going to have to place new binaries in the /home/inspector directory. What if the new binaries are not related to your inspector service ? That's not clean in my opinion. /opt is a standard path used for third party software installation. 

> By the way, for what we may need /opt/etc ?
/opt/etc can be used for storing service specific configuration files in future.

2023-03-06 18:56 UTC, ramizhub commented on systemd/systemdconf.service
> +Group=ramiz
```ramiz@obama:/opt/bin$ ls -lrt
total 52
-rwxr-xr-x 1 inspector inspectorserv 51728 Mar  6 18:39 a.out
```
added new user and new group

2023-03-06 18:57 UTC, ramizhub commented on systemd/systemdconf.service
> +WorkingDirectory=/home/ramiz
changed this .service file

2023-03-06 18:58 UTC, ramizhub commented on systemd/systemdconf.service
> +ExecStart=/home/ramiz/inspector/a.out
Sure! Created /bin/opt and /bin/etc.
Added here my binary file and changed its user and group.

2023-03-07 01:23 UTC, suletm requested changes
Take a look at two more comments I left in this review. Once you fix them feel free to merge with main.

2023-03-07 01:23 UTC, suletm commented on systemd/systemdconf.service
> +Group=inspectorserv
Unless you have a good reason, the group name should be the same as the user.

2023-03-07 01:23 UTC, suletm commented on systemd/systemdconf.service
> +ExecStart=/opt/bin/a.out
Change the name from "a.out" to something more descriptive like "inspectord"

2023-03-07 05:55 UTC, ramizhub commented on systemd/systemdconf.service
> +Group=inspectorserv
I thought it is not recommended. It sounded reasonable because the same names can lead to confusion

2023-03-07 08:42 UTC, suletm commented on systemd/systemdconf.service
> +Group=inspectorserv
No, quite contrary. If there is no good reason of naming them differently, they should be the same. This is a standard way of naming groups.

2023-03-07 12:52 UTC, ramizhub commented on systemd/systemdconf.service
> +ExecStart=/opt/bin/a.out
Changed this line to ```ExecStart=/opt/bin/inspectorbin```

2023-03-07 12:53 UTC, ramizhub commented on systemd/systemdconf.service
> +Group=inspectorserv
You are right, i can see many daemons with same user and group name. Changed it in config and user/group name is ```inspector```.

2023-03-07 13:53 UTC, merged